TEMP: trying to shim WitlessRunner as a Runner for the benchmarks
It is not a full implementation but should suffice to provide at least
optimistic comparison of WitlessRunner (no logging, lines splitting) to Runner.
Unfortunately I am stuck at

$> asv dev --python=same --bench track_overhead_heavyout_online_process
· Discovering benchmarks
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)
[  0.00%] ·· Benchmarking existing-py_home_yoh_proj_datalad_datalad-master_venvs_dev3_bin_python3
[100.00%] ··· core.runner.track_overhead_heavyout_online_process                                                                                                                                                             failed
[100.00%] ···· <function runner.track_overhead_heavyout_online_process.<locals>.<lambda> at 0x7f325abf4680> <class function>
               Traceback (most recent call last):
                 File "/home/yoh/proj/datalad/datalad-master/venvs/dev3/lib/python3.7/site-packages/asv/benchmark.py", line 1184, in main_run_server
                   main_run(run_args)
                 File "/home/yoh/proj/datalad/datalad-master/venvs/dev3/lib/python3.7/site-packages/asv/benchmark.py", line 1058, in main_run
                   result = benchmark.do_run()
                 File "/home/yoh/proj/datalad/datalad-master/venvs/dev3/lib/python3.7/site-packages/asv/benchmark.py", line 537, in do_run
                   return self.run(*self._current_params)
                 File "/home/yoh/proj/datalad/datalad-master/venvs/dev3/lib/python3.7/site-packages/asv/benchmark.py", line 766, in run
                   return self.func(*param)
                 File "/home/yoh/proj/datalad/datalad-master/benchmarks/core.py", line 167, in track_overhead_heavyout_online_process
                   log_online=True)
                 File "/home/yoh/proj/datalad/datalad-master/benchmarks/core.py", line 137, in _get_overhead
                   self.runner.run(cmd, **run_kwargs)
                 File "/home/yoh/proj/datalad/datalad-master/benchmarks/core.py", line 52, in run
                   return super(Runner, self).run(cmd_list, *args, **kwargs)
                 File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 297, in run
                   raise exc_info[1]
                 File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 249, in run
                   processed, unprocessed_len = proc(o[last_idx[i]:])
                 File "/home/yoh/proj/datalad/datalad-master/benchmarks/core.py", line 49, in <lambda>
                   kwargs[proc_] = lambda x: (v(x), 0)
               TypeError: str object is not callable

since not sure why it fails there -- v (which I guess what fails) should be a function,
and proc itself that lambda .... so I am not sure why it fails

[ci skip]